services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Collector\Core\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # configuration document meta data update listeners
  DigitalMarketingFramework\Typo3\Collector\Core\ConfigurationDocument\EventListener\ConfigurationDocumentMetaDataUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\ConfigurationDocument\Event\ConfigurationDocumentMetaDataUpdateEvent

  # registry update listeners
  DigitalMarketingFramework\Typo3\Collector\Core\Registry\EventListener\CollectorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Collector\Core\Registry\Event\CollectorRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Collector\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent
