services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DigitalMarketingFramework\Typo3\Collector\Core\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # registry collection
  DigitalMarketingFramework\Typo3\Collector\Core\Registry\EventListener\RegistryCollectionEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\RegistryCollection

  # registry
  DigitalMarketingFramework\Typo3\Collector\Core\Registry\EventListener\CollectorRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Collector\Core\Registry\Event\CollectorRegistryUpdateEvent

  DigitalMarketingFramework\Typo3\Collector\Core\Registry\EventListener\CoreRegistryUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Registry\Event\CoreRegistryUpdateEvent

  # REST API
  DigitalMarketingFramework\Typo3\Collector\Core\Controller\ContentModifierAjaxController:
    public: true

  # Frontend settings
  DigitalMarketingFramework\Typo3\Collector\Core\Controller\EventListener\FrontendSettingsUpdateEventListener:
    tags:
      - name: event.listener
        event: DigitalMarketingFramework\Typo3\Core\Controller\Event\FrontendSettingsUpdateEvent
